export const siteConfig = {
   name: 'İzmir Araç Yol Yardım',
   description:
      'İzmir ve çevresinde 7/24 profesyonel araç yol yardım hizmeti. Çekici, oto kurtarma, lastik tamiri, akü takviyesi ve daha fazlası.',
   url: 'https://izmir-yol-yardim.com',
   ogImage: 'https://izmir-yol-yardim.com/og-image.jpg',
   keywords: [
      'İzmir yol yardım',
      'İzmir araç çekici',
      'İzmir oto kurtarma',
      'İzmir acil yol yardım',
      'İzmir araç yol yardım',
      'İzmir lastik tamiri',
      'İzmir akü takviyesi',
      'İzmir araç kilidi açma',
      '7/24 yol yardım İzmir',
      'İzmir oto elektrik',
      'Bornova yol yardım',
      'Karşıyaka yol yardım',
      'Konak yol yardım',
      'Buca yol yardım',
      'Çiğli yol yardım',
   ],
   author: 'İzmir Yol Yardım',
   creator: 'İzmir Yol Yardım',

   contact: {
      phone: '+90 532 XXX XX XX',
      email: 'info@izmir-yol-yardim.com',
      address: 'İzmir, Türkiye',
      workingHours: '7/24 Hizmet',
   },

   social: {
      facebook: 'https://facebook.com/izmiryolyardim',
      instagram: 'https://instagram.com/izmiryolyardim',
      twitter: 'https://twitter.com/izmiryolyardim',
      whatsapp: 'https://wa.me/905XXXXXXXXX',
   },

   services: [
      {
         title: 'Araç Çekici Hizmeti',
         description:
            'İzmir genelinde profesyonel araç çekici ve kurtarma hizmeti',
         icon: '🚗',
         slug: 'arac-cekici',
      },
      {
         title: 'Lastik Tamiri ve Değişimi',
         description: 'Acil lastik tamiri, patlak lastik değişimi hizmeti',
         icon: '🔧',
         slug: 'lastik-tamiri',
      },
      {
         title: 'Akü Takviyesi',
         description: '7/24 akü şarjı ve akü takviyesi hizmeti',
         icon: '🔋',
         slug: 'aku-takviyesi',
      },
      {
         title: 'Araç Kilidi Açma',
         description: 'Anahtarınızı unuttuğunuzda profesyonel araç kilidi açma',
         icon: '🔑',
         slug: 'arac-kilidi-acma',
      },
      {
         title: 'Yakıt İkmali',
         description: 'Yolda kaldıysanız acil yakıt ikmali hizmeti',
         icon: '⛽',
         slug: 'yakit-ikmali',
      },
      {
         title: 'Oto Elektrik',
         description: 'Araç elektrik arızalarında yerinde müdahale',
         icon: '⚡',
         slug: 'oto-elektrik',
      },
   ],

   districts: [
      'Aliağa',
      'Balçova',
      'Bayındır',
      'Bayraklı',
      'Bergama',
      'Beydağ',
      'Bornova',
      'Buca',
      'Çeşme',
      'Çiğli',
      'Dikili',
      'Foça',
      'Gaziemir',
      'Güzelbahçe',
      'Karabağlar',
      'Karaburun',
      'Karşıyaka',
      'Kemalpaşa',
      'Kınık',
      'Kiraz',
      'Konak',
      'Menderes',
      'Menemen',
      'Narlıdere',
      'Ödemiş',
      'Seferihisar',
      'Selçuk',
      'Tire',
      'Torbalı',
      'Urla',
   ],

   jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'AutoRepair',
      name: 'İzmir Araç Yol Yardım',
      image: 'https://izmir-yol-yardim.com/logo.jpg',
      '@id': 'https://izmir-yol-yardim.com',
      url: 'https://izmir-yol-yardim.com',
      telephone: '+90 532 XXX XX XX',
      priceRange: '$$',
      address: {
         '@type': 'PostalAddress',
         streetAddress: 'İzmir',
         addressLocality: 'İzmir',
         postalCode: '35000',
         addressCountry: 'TR',
      },
      geo: {
         '@type': 'GeoCoordinates',
         latitude: 38.4237,
         longitude: 27.1428,
      },
      openingHoursSpecification: {
         '@type': 'OpeningHoursSpecification',
         dayOfWeek: [
            'Monday',
            'Tuesday',
            'Wednesday',
            'Thursday',
            'Friday',
            'Saturday',
            'Sunday',
         ],
         opens: '00:00',
         closes: '23:59',
      },
      sameAs: [
         'https://facebook.com/izmiryolyardim',
         'https://instagram.com/izmiryolyardim',
         'https://twitter.com/izmiryolyardim',
      ],
   },
};

export type SiteConfig = typeof siteConfig;
